<<<<<<< HEAD
# config/routes.yaml
=======
>>>>>>> origin/gestionComptesOperation
controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
